### ISSUE TITLE
Black Border to Mini Cursor

### ISSUE THREAD

**Issue by kairo741** [makipom/BlueArchive-Cursors#15]
I really like the Blue Archive Mini Cursor, but i keep losing it in my screen. Could you make a version with a black border in it? Like the Milllenium

**Comment by makipom** [comment]
The Blue Archive cursor set labeled as "Regular Edition" in the README.md is made following the same design philosophy used in the cursors for the official Chinese website for the game (linked in the "Credits" section). 
From there, a set of issues arose with these cursors, including poor visibility on certain display settings or over certain backgrounds, due to the cursor's color palette. (e.g. #13 )
As a way to combat such issues, I created the "Millennium Edition" cursor set, which takes several liberties with the design to improve on the user experience. 
Hence, I stand by what I said in the Issue 13. The "Regular Edition" was made as closely as possible to the official cursors, as such **it is working as intended.** If you such problems are occurring frequently on your end and are disturbing to your experience, I strongly advise you to please try the "Millennium Edition" cursors. While it is larger than the "Mini" set for the "Regular Edition", I believe it should be smaller than the general ones, and "Millennium Edition" also has much more customization options for you to choose from.
